feat: arrays support for setVariable
defi-wonderland/smock pull request #144
Opened 2022-07-29 15:11 UTC by tonykogias

**Description**
Add support for arrays on `setVariable` for Mock contracts.

**Metadata**

- Fixes #31

2022-07-29 15:18 UTC, 0xGorilla commented on src/utils/storage.ts
> +      throw new Error(`variable is an array but has no base: ${variableType}`);
How is this fixable from a user standpoint?

2022-07-29 15:35 UTC, wei3erHase commented on test/contracts/mock/StorageGetter.sol
> +  uint16[][] internal _uint2DArray;
blz try with `int16` and use negative numbers :)

2022-07-29 15:36 UTC, wei3erHase commented on test/unit/mock/editable-storage-logic.spec.ts
> +      ]);
wowowowowowowo 🚀

2022-07-29 16:19 UTC, 0xGorilla commented on src/utils/storage.ts
> +    slots = slots.concat({
Let's add the object in initialisation:

```typescript
let slots: StorageSlotPair[] = [{
    key: slotKey,
    val: padNumHexSlotValue(variable.length, 0),
}];
```

2022-07-29 16:20 UTC, 0xGorilla commented on src/utils/storage.ts
> +      // If the values are pakced then we need to keep track of the offset and when to change slot
```suggestion
      // If the values are packed then we need to keep track of the offset and when to change slot
```

2022-07-29 16:21 UTC, 0xGorilla requested changes
This is 🔥

2022-08-01 10:55 UTC, 0xGorilla commented on test/unit/mock/editable-storage-logic.spec.ts
> +      ]);
```suggestion
      const arr = [
        [-1, -2],
        [-3, -4],
        [5, -6],
      ];
      await mock.setVariable('_int2DArray', arr);
      expect(await mock.getInt2D16Array()).to.eql(arr);
```

2022-08-01 11:00 UTC, 0xGorilla approved these changes

2022-08-01 11:01 UTC, merged

2022-08-02 05:05 UTC, murderteeth commented
thanks @tonykogias !